name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
        target: [lib, exe, daemon, deb]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cargo-${{ matrix.arch }}
          key: ${{ matrix.arch }}-${{ hashFiles('Cargo.lock') }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Build
        run: make TARGET=${{ matrix.arch }} ${{ matrix.target }}
      - name: Fix cache permission
        run: sudo chown -R $USER .cargo-${{ matrix.arch }}
      - uses: actions/upload-artifact@v3
        if: matrix.target == 'deb'
        with:
          name: sectora-${{ matrix.arch }}
          path: ${{ github.workspace }}/target/*/debian/*.deb

  set-dists:
    runs-on: ubuntu-latest
    outputs:
      dists: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          content=$(curl -L https://raw.githubusercontent.com/yasuyuky/docker-ssh-test/main/dist.json | jq -c .)
          echo matrix=${content} >>$GITHUB_OUTPUT
          echo ${content}

  test:
    needs: [build, set-dists]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-dists.outputs.dists) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: sectora-amd64
          path: target
      - name: Run tests
        run: make test-deb-stub dist=${{ matrix.dist }} ver=${{ matrix.ver }}
        working-directory: test
        env:
          TERM: xterm-256color
