name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Date
        id: get_date
        run: |
          date +'%Y.%m.%d'
          echo date=$(date +'%Y.%m.%d') >>$GITHUB_OUTPUT

      - name: Get the version in cargo
        id: cargo_ver
        run: |
          VERSION=$(grep '^version' Cargo.toml | cut -d '"' -f 2)
          echo ${VERSION}
          echo version=${VERSION} >>$GITHUB_OUTPUT
          echo v=v${VERSION} >>$GITHUB_OUTPUT
          test ${GITHUB_REF/refs\/tags\//} = v${VERSION}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.cargo_ver.outputs.v }}
          release_name: Release ${{ steps.cargo_ver.outputs.v }} (${{ steps.get_date.outputs.date }})
          body: Automated release
          draft: false
          prerelease: false

      - name: Build deb
        run: make deb

      - name: Upload Release Asset x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/x86_64-unknown-linux-gnu/debian/sectora_${{ steps.cargo_ver.outputs.version }}_amd64.deb
          asset_name: sectora_${{ steps.cargo_ver.outputs.version }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload Release Asset arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/arm-unknown-linux-gnueabihf/debian/sectora_${{ steps.cargo_ver.outputs.version }}_armhf.deb
          asset_name: sectora_${{ steps.cargo_ver.outputs.version }}_armhf.deb
          asset_content_type: application/vnd.debian.binary-package
